baseURL = "https://nalsai.de/"
title = "Nils' Website"
enableGitInfo = true
DefaultContentLanguage = "en"

[languages]
  [languages.en]
    baseURL = "https://en.nalsai.de"
    contentDir = "content/en"
    languageCode = 'en-US'
    languageName = "English"
    title = "Nils' Website"
    weight = 1
  [languages.de]
    baseURL = "https://nalsai.de"
    contentDir = "content/de"
    languageCode = 'de-DE'
    languageName = "Deutsch"
    title = "Nils' Webseite"
    weight = 2

[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true

[taxonomies]
  tag = "tags"

[outputs]
  home = ['html', 'rss']
  page = ['html']
  rss = ['rss']
  section = ['html', 'rss', 'json']
  taxonomy = ['html', 'rss']
  term = ['html', 'rss']

[params]
  [params.umami]
    id = "b0d36943-ce3a-42e9-ae7e-c3c7209594db"
    src = "https://umami.nils.moe/script.js"
  [params.remark42]
    host = "https://r42.nalsai.de"
    site = "nalsai"

[module]
  [[module.imports]]
    path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
